Add ignore case option
obreitwi/vim-sort-folds pull request #3
Opened 2020-09-15 18:26 UTC by roosta

I don't know if this is of any interest to you, but I needed to be able to sort case insensitive. I'm no python or vimscript wizard but this has worked for me pretty well. Love your plugin, saved me a lot of time.

2020-09-16 07:49 UTC, obreitwi commented
Hey, glad you like the plugin and thank you for your contribution. This addition is definitely of interest! :+1: 

However, I think instead of one configuration variable with single character flags it would be better to have a more expressive setting like `g:sort_folds_ignore_case` that defaults to `0` but could be set non-zero by the user.

The python-part could read this setting via `vim.command("echo g:sort_folds_ignore_case")` whereas the vimscript would have to make sure the default exists.

2020-09-16 08:16 UTC, roosta commented
I'll go about making those changes later today, thank you for your feedback.

2020-09-16 08:28 UTC, roosta commented
Question: I saw your commit https://github.com/obreitwi/vim-sort-folds/commit/502014917c240f98a9fe49e809fcc3ea6e5e0131and was wondering if you only target python3? there are some more changes I can make if this is the case, namely replacing
```python
lambda f: f[sort_line].lower()
```
With this function
```python
str.casefold
```

2020-09-16 08:54 UTC, obreitwi commented
> Question: I saw your commit 5020149 was wondering if you only target python3?

Yes, ever since merging 0af27b1 sort-folds requires python 3. It should therefore move from using the `pythonx`-provider to using `python3` because I originally intended for it to be compatible with both versions. However, nowadays python 2 is finally being phased out so there is no need to maintain compatibility.

2020-09-16 15:31 UTC, roosta commented
OK, I've updated the pull request with your suggested changes

2020-09-17 07:14 UTC, obreitwi commented on README.md
> +Defaults is `0`
```suggestion
Default is `0`
```

2020-09-17 07:22 UTC, obreitwi requested changes
Thank you for your change. Just have some minor naming-related suggestion.

Other than that it is really apparent that the code base needs an overhaul :o)

2020-09-17 07:22 UTC, obreitwi commented on pythonx/SortFolds/__init__.py
> +def sorter(sort_line):
`sorter` suggests that the function sorts like `sort_folds`. Would rename it to something like `get_fold_to_sort_key` so that it is clear that the function generates a function to be used as `key`-attribute in `sorted`.

2020-09-17 08:22 UTC, roosta commented
The requested changes are made

2020-09-17 08:37 UTC, obreitwi approved these changes
Thank you!

2020-09-17 08:38 UTC, merged

2020-09-17 08:40 UTC, roosta commented
Thank you for considering this addition :)